version: '2.1'

services:
  master:
    image: ${IMAGE:-mysql}
    container_name: master
    volumes:
      - ./initdb/master/:/docker-entrypoint-initdb.d/
      - .:/work
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --binlog-format=${BINLOG_FORMAT:-row} --log-bin=mysql-bin --local-infile=true --server-id=101
  slave:
    image: ${IMAGE:-mysql}
    container_name: slave
    volumes:
      - ./initdb/slave/:/docker-entrypoint-initdb.d/
      - .:/work
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --binlog-format=${BINLOG_FORMAT:-row} --log-bin=mysql-bin --local-infile=true --server-id=102

